grpc:
  client:
    grpc-treeleaf-service:
      address: static://localhost:9000
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

